In [5]:
import pandas as pd
from collections import defaultdict
from tqdm import tqdm

# modify

SPD.csvで文字列を読むため','分割から'\t,\t'へ

In [6]:
with open('/home/tamak/experiments/spotify_dataset.csv', mode = 'r') as f:
    lines = f.readlines()

with open('./spotify_playlists_dataset/SPD_modified.tsv', mode = 'w') as f2:

    f2.write('user_id\t,\tartistname\t,\ttrackname\t,\tplaylistname\n')
    for line in lines[1:]:
        data = line[1:-1].split('","')

        if len(data)!= 4 :
            print(data)

        else:
            f2.write( data[0]+'\t,\t'+data[1]+'\t,\t'+data[2]+'\t,\t'+data[3][:-1]+'\n' )

In [7]:
df = pd.read_csv('./spotify_playlists_dataset/SPD_modified.tsv', sep = '\t,\t')
df

/tmp/ipykernel_33222/527892708.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('./spotify_playlists_dataset/SPD_modified.tsv', sep = '\t,\t')

,user_id,artistname,trackname,playlistname
0,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello,(The Angels Wanna Wear My) Red Shoes,HARD ROCK 2010
1,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello & The Attractions,"(What's So Funny 'Bout) Peace, Love And Unders...",HARD ROCK 2010
2,9cc0cfd4d7d7885102480dd99e7a90d6,Tiffany Page,7 Years Too Late,HARD ROCK 2010
3,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello & The Attractions,Accidents Will Happen,HARD ROCK 2010
4,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello,Alison,HARD ROCK 2010
...,...,...,...,...
12902572,2302bf9c64dc63d88a750215ed187f2c,Mötley Crüe,Wild Side,iPhone
12902573,2302bf9c64dc63d88a750215ed187f2c,John Lennon,Woman,iPhone
12902574,2302bf9c64dc63d88a750215ed187f2c,Tom Petty,You Don't Know How It Feels,iPhone
12902575,2302bf9c64dc63d88a750215ed187f2c,Tom Petty,You Wreck Me,iPhone
12902576,2302bf9c64dc63d88a750215ed187f2c,Skid Row,Youth Gone Wild,iPhone

In [8]:
track_dict = defaultdict(int)

with open('./spotify_playlists_dataset/SPD_modified.tsv', mode = 'r') as f:

    lines = f.readlines()

for line in lines[1:]:
    data = line.split('\t,\t')

    track = (data[1],data[2])

    if track not in track_dict:
        track_dict[track] = len(track_dict)

SPDからユーザ-プレイリストのデータへ

In [9]:
#user and playlist pair dict
tmp_list = []
user_playlist_pairs = defaultdict(list)
user = ''
playlist = ''

with open('./spotify_playlists_dataset/SPD_modified.tsv', mode = 'r') as f:

    lines = f.readlines()


with open('./spotify_playlists_dataset/user_playlist_pairs.tsv', mode='w') as f:
    for line in tqdm(lines[1:]):

        data = line[:-1].split('\t,\t')
        if user != data[0] or playlist != data[3] :
            f.write('\n')
            user = data[0]
            playlist = data[3]
            f.write(user+'\t,\t'+playlist)
        
        track = ( data[1], data[2] )
        f.write('\t,\t'+str(track_dict[track]))

100%|██████████| 12902577/12902577 [00:15<00:00, 821013.16it/s]

ユーザid-プレイリストのデータからユーザid-トラックid-label(1)のデータへ

In [11]:
with open('./spotify_playlists_dataset/user_playlist_pairs.tsv', mode = 'r') as f:

    lines = f.readlines()


with open('./spotify_playlists_dataset/session_data.tsv', mode = 'w') as f:
    f.write('userId\ttrackId\tlabel\n')

    for line in tqdm(lines[1:]):
        data = line.split('\t,\t')
        user = data[0]
        session = data[2:]

        for track in session:
            f.write( user+'\t'+track.removesuffix('\n')+'\t'+str(1)+'\n' )

100%|██████████| 232149/232149 [00:06<00:00, 38351.73it/s]

In [12]:
df = pd.read_csv('./spotify_playlists_dataset/session_data.tsv', sep = '\t')
df[:10]

                             userId  trackId  label
0  9cc0cfd4d7d7885102480dd99e7a90d6        0      1
1  9cc0cfd4d7d7885102480dd99e7a90d6        1      1
2  9cc0cfd4d7d7885102480dd99e7a90d6        2      1
3  9cc0cfd4d7d7885102480dd99e7a90d6        3      1
4  9cc0cfd4d7d7885102480dd99e7a90d6        4      1
5  9cc0cfd4d7d7885102480dd99e7a90d6        5      1
6  9cc0cfd4d7d7885102480dd99e7a90d6        6      1
7  9cc0cfd4d7d7885102480dd99e7a90d6        7      1
8  9cc0cfd4d7d7885102480dd99e7a90d6        8      1
9  9cc0cfd4d7d7885102480dd99e7a90d6        9      1